version: "3"

services:
  catcat-img-service:
    container_name: catcat-img-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PORT=${PORT:-3000}
    image: catcatio/imgservice
    working_dir: /usr/app
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - .:/usr/app
    command: npm run init
